ORIGINAL_PATH=$PATH

POSTGRES_SPRINGBOOT_DESTINATION_VERSION=$POSTGRES_VERSION
POSTGRES_SPRINGBOOT_SOURCE_NAME=$POSTGRES_DB
POSTGRES_SPRINGBOOT_DESTINATION_NAME=$POSTGRES_SPRINGBOOT_SOURCE_NAME
POSTGRES_SPRINGBOOT_DESTINATION_PORT=$(grep 'port = ' $HOME/workspace/myProjects/config-samples/$OS/postgres/$POSTGRES_SPRINGBOOT_DESTINATION_VERSION/postgresql.conf | awk '{print $3}')
POSTGRES_SPRINGBOOT_DESTINATION_PASSWORD=password
POSTGRES_SPRINGBOOT_DESTINATION_USER=shreyas

export PATH=$HOME/programs/postgres/$POSTGRES_SPRINGBOOT_DESTINATION_VERSION/bin:$ORIGINAL_PATH
printf "Restoring for $POSTGRES_SPRINGBOOT_SOURCE_NAME\n"
PGPASSWORD=$POSTGRES_SPRINGBOOT_DESTINATION_PASSWORD dropdb -p $POSTGRES_SPRINGBOOT_DESTINATION_PORT -U $POSTGRES_SPRINGBOOT_DESTINATION_USER $POSTGRES_SPRINGBOOT_DESTINATION_NAME
PGPASSWORD=$POSTGRES_SPRINGBOOT_DESTINATION_PASSWORD createdb -p $POSTGRES_SPRINGBOOT_DESTINATION_PORT -U $POSTGRES_SPRINGBOOT_DESTINATION_USER $POSTGRES_SPRINGBOOT_DESTINATION_NAME
PGPASSWORD=$POSTGRES_SPRINGBOOT_DESTINATION_PASSWORD psql -p $POSTGRES_SPRINGBOOT_DESTINATION_PORT -U $POSTGRES_SPRINGBOOT_DESTINATION_USER -d $POSTGRES_SPRINGBOOT_DESTINATION_NAME -f $HOME/dbBackups/$POSTGRES_SPRINGBOOT_SOURCE_NAME.sql > /dev/null 2>&1
